version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-htmx-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.configureondemand=true"
    volumes:
      # Share Gradle cache between builds
      - gradle-cache:/home/app/.gradle
      # Share source code for hot reloading
      - ./:/app
      # Share Gradle daemon process
      - ~/.gradle/daemon:/home/app/.gradle/daemon
      # Development-specific volume for Spring DevTools
      - ./build/classes:/app/build/classes

volumes:
  gradle-cache:
    name: gradle-cache