version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-htmx-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      # Share Gradle cache between builds
      - gradle-cache:/home/gradle/.gradle
      # If you need to share the local .gradle cache with the container
      # - ~/.gradle:/home/gradle/.gradle

volumes:
  gradle-cache:
    name: gradle-cache