
preponderous:
  company:
    name: "Preponderous Software"
    description: "Developing free and open-source games and assets"
    github-link: "https://github.com/Preponderous-Software"
  projects:
    - title: "Apex-Ecosystem-Simulator"
      description: "Observe the activity of a virtual environment containing entities that depend on each other as sources of energy."
      github-link: "https://github.com/Preponderous-Software/Apex-Ecosystem-Simulator"
      technology: "Python"

    - title: "Beyond-Nations"
      description: "Sandbox Nation Simulation RPG"
      github-link: "https://github.com/Preponderous-Software/Beyond-Nations"
      technology: "C#"

    - title: "env-lib-cpp"
      description: "Provides base classes for creating two-dimensional virtual worlds."
      github-link: "https://github.com/Preponderous-Software/env-lib-cpp"
      technology: "C++"

    - title: "microbiome"
      description: "Witness the activity of a virtual microbial community."
      github-link: "https://github.com/Preponderous-Software/microbiome"
      technology: "C++"

    - title: "Ophidian"
      description: "Control an ever-increasingly growing ophidian in a virtual environment."
      github-link: "https://github.com/Preponderous-Software/Ophidian"
      technology: "Python"

    - title: "Patchwork"
      description: "Patchwork is a lightweight tool for visualizing 2D environments, built with Python."
      github-link: "https://github.com/Preponderous-Software/Patchwork"
      technology: "Python"

    - title: "preponderous-website"
      description: "Official website for Preponderous Software"
      github-link: "https://github.com/Preponderous-Software/preponderous-website"
      technology: "HTML"

    - title: "py_env_lib"
      description: "Provides base classes for creating two-dimensional virtual worlds."
      github-link: "https://github.com/Preponderous-Software/py_env_lib"
      technology: "Python"

    - title: "Roam"
      description: "Explore a procedurally-generated 2D world and interact with your surroundings."
      github-link: "https://github.com/Preponderous-Software/Roam"
      technology: "Python"

    - title: "Viron"
      description: "Viron is a flexible simulation framework for building and managing 2D virtual environments."
      github-link: "https://github.com/Preponderous-Software/Viron"
      technology: "Java"