preponderous:
  company:
    name: "Preponderous Software"
    description: "Developing free and open-source games and assets"
    github-link: "https://github.com/Preponderous-Software"
  projects:
    - title: "Beyond Nations"
      description: "A sandbox nation simulation RPG that allows players to explore a procedurally generated world, collect resources, and interact with various entities."
      github-link: "https://github.com/Preponderous-Software/Beyond-Nations"
      technology: "Java"
    - title: "Viron"
      description: "A tool for creating and managing virtual environments and entities within those environments, intended for game development and other applications."
      github-link: "https://github.com/Preponderous-Software/Viron"
      technology: "Java"